<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Trx\ActiveAssessmentController;
use App\Http\Controllers\Trx\AssessmentHelpController;
use App\Http\Controllers\Trx\DelegationController;
use Illuminate\Support\Facades\Route;

/*
| Web routes
| - Auth routes are generated by Laravel Breeze.
| - Additional pages follow the spec:
|   /adm/* for admin masters
|   /trx/* for transactions
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::middleware(['auth', 'force.password.change'])->group(function () {
    Route::get('/help', [AssessmentHelpController::class, 'index'])->name('help');

    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/change-password', [ProfileController::class, 'changePassword'])->name('password.edit');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::patch('/profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Admin pages
    Route::prefix('adm')->middleware('admin.only')->group(function () {
        Route::view('/sections', 'admin.sections')->name('adm.sections');
        Route::view('/categories', 'admin.categories')->name('adm.categories');
        Route::view('/indicators', 'admin.indicators')->name('adm.indicators');
        Route::view('/sub-indicators', 'admin.sub_indicators')->name('adm.sub_indicators');
        Route::view('/users', 'admin.users')->name('adm.users');
    });

    // Transaction pages
    Route::prefix('trx')->group(function () {
        Route::get('/', fn () => redirect()->route('trx.active'))->name('trx.index');
        Route::get('/active', [ActiveAssessmentController::class, 'index'])->name('trx.active');
        Route::get('/delegation', [DelegationController::class, 'index'])->name('trx.delegation.index');
        Route::post('/delegation', [DelegationController::class, 'store'])->name('trx.delegation.store');
        Route::put('/delegation/{id}', [DelegationController::class, 'update'])->name('trx.delegation.update');
        Route::delete('/delegation/{id}', [DelegationController::class, 'destroy'])->name('trx.delegation.destroy');

        Route::middleware('admin.only')->group(function () {
            Route::view('/periods', 'trx.periods')->name('trx.periods');
            Route::view('/period/{periodId}/countries', 'trx.period_countries')->name('trx.period_countries');
        });

        Route::view('/country', 'dashboard')->name('trx.country_list');
        Route::view('/form', 'trx.assessment_form')->name('trx.form');
    });
});

require __DIR__.'/auth.php';
