<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
| Web routes
| - Auth routes are generated by Laravel Breeze.
| - Additional pages follow the spec:
|   /adm/* for admin masters
|   /trx/* for transactions
*/

Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::middleware(['auth'])->group(function () {
    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Admin pages
    Route::prefix('adm')->middleware('admin.only')->group(function () {
        Route::view('/sections', 'admin.sections')->name('adm.sections');
        Route::view('/categories', 'admin.categories')->name('adm.categories');
        Route::view('/indicators', 'admin.indicators')->name('adm.indicators');
        Route::view('/sub-indicators', 'admin.sub_indicators')->name('adm.sub_indicators');
        Route::view('/users', 'admin.users')->name('adm.users');
    });

    // Transaction pages
    Route::prefix('trx')->group(function () {
        Route::middleware('admin.only')->group(function () {
            Route::view('/periods', 'trx.periods')->name('trx.periods');
            Route::view('/period/{periodId}/countries', 'trx.period_countries')->name('trx.period_countries');
        });

        Route::view('/country', 'trx.country_list')->name('trx.country_list');
        Route::view('/form', 'trx.assessment_form')->name('trx.form');
    });
});

require __DIR__.'/auth.php';
